[tool.poetry]
name = "zygoat"
version = "0.1.0"
description = ""
authors = ["Bequest, Inc. <oss@willing.com>"]

[tool.poetry.dependencies]
python = "^3.6"
click = "^7.0"
colorama = "^0.4.3"
"ruamel.yaml" = "^0.16.10"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
flake8 = "^3.7"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
